#!/bin/sh

set -e

# check if dependencies are installed
missing_deps=false
for dep in $(cat ./dependencies); do
	if [ ! -e "/usr/bin/$dep" ]; then
		missing_deps=true
		echo "Dependency $dep is not installed!"
	fi

done

TARGET=/usr/bin/vmt

if [ "$(whoami)" != "root" ]; then
	echo "Insufficient permissions. Execute as root..."
	exit 1
fi

mkdir -p tools os iso

echo "#!/bin/sh" > $TARGET
echo "eval $(pwd)/select_tool \$@" >> $TARGET
echo "Created $TARGET"
chmod -v a+x $TARGET

echo "vmt installed successfully!"
echo "Usage: vmt [tool]"
