#!/bin/sh

cd $(dirname $0)

export DEF_CORES=$(cat ./config/def_cores)
export DEF_MEM=$(cat ./config/def_mem)

if [ -z "$1" ]; then
	TOOL=$(ls tools | fzf --header "Select tool")
else
	TOOL=$(ls tools | grep $1)
fi

if [ ! -z "$TOOL" ]; then
	eval tools/$TOOL $@
else
	echo "No tool found..."
fi
