#!/bin/sh

set -e

if [ -z "$2" ]; then
	SELECTED_OS=os/$(ls os | fzf --header "Select OS")
else 
	SELECTED_OS=$2
fi

echo -n "Are you sure you want to delete $SELECTED_OS? (y/N): "
read CONFIRM
if [ "$CONFIRM" == "y" ]; then
	rm -rvf $SELECTED_OS
fi
