#!/bin/sh

set -e

get_url() {
	while :; do
		echo -n 'Enter URL to .iso: '
		read ISO_URL
		if [ ! -z "$ISO_URL" ]; then
			break
		fi
	done
}

get_url
cd iso
echo "Downloading $ISO_URL..."
wget -v $ISO_URL
echo "Download successful!"
cd ..
