#!/bin/sh

set -e

if [ ! -x "/usr/bin/fzf" ]; then
	echo "Please install fzf..."
	exit 1
fi

if [ -z "$(groups $USER | grep kvm)" ]; then
	echo "You aren't a part of the KVM group..."
	echo "To use kvm, execute this as root: (and you might need to reboot)"
	echo "usermod -aG kvm $USER"
	exit 1
fi

if [ ! -r "/dev/kvm" ] || [ ! -w "/dev/kvm" ]; then
	echo "You don't have r/w permissions for kvm:"
	ls -l /dev/kvm
	exit 1
fi

if [ -z "$(lsmod | grep kvm)" ]; then
	echo "No kvm modules detected... Try this (as root):"
	echo "'modprobe kvm'"
	echo "'modprobe kvm_intel' (for intel)"
	echo "'modprobe kvm_amd' (for amd)"
fi

if [ -z "$2" ]; then
	OS=os/$(ls os | fzf --header "Select OS")
else
	OS=os/$(ls os | grep "$2")
fi

DISK=$OS/disks/$(ls $OS/disks | fzf --header "Select disk image")

echo -n "How many threads? (you have $(nproc)) [$DEF_CORES]: "
read CORES
[ -z "$CORES" ] && CORES=$DEF_CORES

echo -n "How much memory? (you have $(free --giga -h | grep Mem | awk '{print $2}')) [$DEF_MEM]: "
read MEM
[ -z "$MEM" ] && MEM=$DEF_MEM

QEMU_CMD="qemu-system-x86_64 \
	-enable-kvm \
	-smp $CORES \
	-m $MEM \
	-drive file=$DISK"

echo -n "Use cdrom? [y,N]: "
read USE_CDROM
if [ "$USE_CDROM" == "y" ]; then
	ISO=iso/$(ls iso | fzf --header "Select ISO")
	QEMU_CMD="$QEMU_CMD -cdrom $ISO"
	echo -n "boot from cdrom? [y,N]: "
	read BOOT_CDROM
	if [ "$BOOT_CDROM" == "y" ]; then
		QEMU_CMD="$QEMU_CMD -boot d"
	fi
fi

eval $QEMU_CMD &
